photo/urls.py
from django.urls import path 
from .import views


app_name = 'photo'

urlpatterns = [
    path('',views.home,name='home'),
    path('<int:pk>/',views.detail,name='detail'),
    path('add/',views.addPhoto,name='add'),
]

photoshare/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photo.urls',namespace='photo'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.urls import reverse



class Category(models.Model):
    name= models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name_plural='categroies'


    # def __str__(self):
    #     return self.name


    




class Photo(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category,related_name='photo',on_delete=models.CASCADE,null=True)
    description = models.TextField()
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='image/%Y/%m/%d/')

    

photo/views.py
from django.shortcuts import render , redirect
from .models import Category , Photo

def home(request):
    category = request.GET.get('category')
    
    if category == None :
        photos = Photo.objects.all()
    else:
       photos = Photo.objects.filter(category__name=category)

    categories = Category.objects.all()

    return render(request,'photo/home.html',{'photos':photos,'categories':categories})



def detail(request,pk):
    photo= Photo.objects.get(id=pk)


    return render(request,'photo/detail.html',{'photo':photo})




def addPhoto(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images') #list of  images 

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('photo:home')

    context = {'categories': categories}
    return render(request, 'photo/add.html', context)

photo/templates/photo/add.html
{% extends 'base.html' %}
{% block content %}





  <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-4">
                <a href="{% url 'photo:home' %}" class="btn btn-dark my-3">Go Back</a>
                <div class="card">


                    <form method='POST' action="" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group m-3">
                            <label>Description</label>
                            <input required name="description" type="text" placeholder="Enter a description"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Select a category</label>
                            <select name="category" class="form-control">
                                <option value='none'>Select a category...</option>

                                {% for category in categories %}
                                <option value='{{category.id}}'>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group m-3">
                            <label>Create a new category</label>
                            <input name="category_new" type="text" placeholder="Create a new category"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Upload image</label>
                            <input required name="images" type="file" multiple class="form-control-file">
                        </div>

                        <button type='submit' class="btn btn-primary m-3">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}

{% block content %}




<div class="row">
  <div class="col-xs-6 col-md-3">
     <img src="{{ photo.image.url }}" alt="" width="400px" height="300px">
     <h4>{{photo.name}}</h4>
     </hr>
     <p>
     {{photo.description}}</p>
     <p>{{photo.date}}</p>
  </div>
</div>





{% endblock %}

photo/templates/photo/home.html
{% extends "base.html" %}
{% load static %}

{% block content%}




 <div class="btn-group">
            <a href="{% url 'photo:home' %}" class="btn btn-danger">All</a>
        </div>



{% for category in categories %}

        <div class="btn-group">
            <a href="{% url 'photo:home' %}?category={{category.name}}" class="btn btn-danger">{{ category.name }}</a>
             
            
        </div>


{% endfor %}</br></br>



<a href="{% url 'photo:add' %}" id="sina" class="btn btn-primary">Add Photo</a>



{% for photo in photos %}



<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="{% url 'photo:detail' photo.id %}" class="thumbnail">
     <img src="{{ photo.image.url }}" alt="" width="400px" height="300px">
    </a>
  </div>
</div>
 

{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
   
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }

        .list-group-item a {
            text-decoration: none;
            color: black;
        }
    </style>

</head>
    


<body>
    <div>
        {% include 'inc/messages.html' %}
    {%block content%}   {%endblock%}
    </div>

</body>

templates/inc/messages.html
{% if messages %}

{% for msg in messages %}


<p class="alert alert-{{msg.tags}}">{{msg}}</p>


{% endfor %}




{% endif %}